export const solarized_light = {
    theme_type: "light",
    quizletPurple: "#268bd2",
    quizletPurpleAccents: "#2aa198",
    quizletFont: "white",
    mainAccent: "#b58900",
    accentFont: "white",
    body: "#eee8d5",
    notesBackground: "#fdf6e3",
    notesColor: "#586e75",
    code: "#eee8d5",
    miscButtons: "#eee8d5",
    buttonsColor: "black",
    contextMenu: "#eee8d5",
    contextMenuColor: "black",
    sidebarAccents: "#93a1a1",
    sideBar: "#eee8d5",
    listBackground: "#fdf6e3",
    searchAndUpload: "#268bd2",
    searchAndUploadColor: "white",
    listColor: "#586e75",
    icons: "#268bd2",
    iconsColor: "white",
    tabColor: "black",
    droppedFolders: "#eee8d5",
    hovers: "#93a1a1",
    destructive: "#dc322f",
    popupHeader: "rgba(253, 246, 227, 0.7)",
    popupExit: "#dc322f",
    highlight: "#b58900",
    highlightColor: "white",
    selection: "#eee8d5",
    floatingBs: "rgba(0, 0, 0, 0.24) 0px 3px 8px",
  };